server:
  port: 8083
spring:
  upload:
    url: C:\Users\86180\Desktop\hmdp-nginx-1.18.0\nginx-1.18.0\html\hmdp\imgs\
  rabbitmq:
    host: 192.168.5.27
    port: 5672
    username: LuciusWan
    password: Wwwaxk12345@
    virtual-host: /
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
